# Pipeline for creating and pushing Cloud Run artifacts

trigger:
  branches:
    include:
      - main
      - adding-ci-cd
  paths:
    include:
      - 'api/*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'api'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/jpo_cvmanager_api'

  # Publish the artifacts directory for consumption in publish pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'docker_run'
      publishLocation: 'Container'
